server:
  port: 5002
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employee?useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: employee-module
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 3302983
mybatis:
  type-aliases-package: com.windhide.employee.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.windhide.employee: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
