server:
  port: 5003 # 网关端口
spring:
  application:
    name: auth-module # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 3302983