server:
  port: 10010 # 网关端口
spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 3302983
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
  application:
    name: gateway-module # 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: abonement-module
          uri: lb://abonement-module
          predicates:
            - Path=/order/**,/shoppingCart/**,/user/**,/userLevel/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/activity/**,/dictionaries/**,/employee/**,/employeeType/**,/goods/**,/goodsType/**,/incomeState/**
