server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway-module # 服务名称
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 3302983
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: abonement-module
          uri: lb://abonement-module
          predicates:
            - Path=/orderDetail/**,/shoppingCart/**,/user/**,/userLevel/**,/desk/**
        - id: employee-module
          uri: lb://employee-module
          predicates:
            - Path=/activity/**,/dictionaries/**,/employee/**,/employeeType/**,/goods/**,/goodsType/**,/incomeState/**,/uploadRemove/**,/upload/**
        - id: auth-module
          uri: lb://auth-module
          predicates:
            - Path=/auth/**
        - id: static-resources
          uri: lb://employee-module
          predicates:
            - Path=/static/**
          filters:
            - StripPrefix=1