server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway-module # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: abonement-module
          uri: lb://abonement-module
          predicates:
            - Path=/order/**,/shoppingCart/**,/user/**,/userLevel/**
        - id: employee-module
          uri: lb://employee-module
          predicates:
            - Path=/activity/**,/dictionaries/**,/employee/**,/employeeType/**,/goods/**,/goodsType/**,/incomeState/**
        - id: static-resources
          uri: lb://employee-module
          predicates:
              - Path=/static/**
          filters:
            - StripPrefix=1